version: 2.1

jobs:
    build:
      docker:
        - image: jimtin/cff_windowsforensicsgatherer
#jobs:
#  build:
#    docker:
#      - image: jimtin/cff_windowsforensicsgatherer

    # Set the working directory
    working_directory: "C:\\WindowsForensicsGatherer\\CFF_WindowsForensicsGatherer-master"

    # Run tests
    - run:
      name: run tests
      command: Invoke-Pester "C:\\WindowsForensicsGatherer\\CFF_WindowsForensicsGatherer-master\\Tests\\inittest.Tests.ps1"
