# State the version of CircleCI to use
version: 2.1

# Select the windows Orb, which also includes Docker
orbs:
  win: circleci/windows@2.4.0

# Set up the workflow
workflows:
  build:
    jobs:
      - build:
          context: cff_context

# Run the testing
jobs:
  build:
    # Set up executor
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      # Checkout the repo
      - checkout
      - run: systeminfo
      
      # Set up the Windows Server
      - run:
          name: "Set up Windows Server"
          shell: powershell.exe
          command: |
            Set-LocalUser -Name $env:USERNAME -Password ""
            Add-LocalUser -Group "Administrators" -Name $env:USERNAME
            Enable-PSRemoting -Force
            Install-Module Pester -Force
            
      # Build the cff_windowsforensicsgatherer docker
      #- run:
      #    name: "Build CFF_WindowsForensicsGatherer"
      #    shell: powershell.exe
      #    command: |
      #      docker build -t windowsforensicsgatherer .
    
      # Run the CI tests script
      #- run: 
      #    name: "Run CI tests"
      #    shell: powershell.exe
      #    command: |
      #      .\Tests\runCITests.ps1
