version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Build CFF_WindowsForensicsGatherer"
          shell: powershell.exe
          command: |
            docker build -t windowsforensicsgatherer .
            docker run -e Target="NowWeHaveATarget" -e Playbook="NowWeHaveATarget" -t windowsforensicsgatherer
